home/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

urlpatterns =[
    url(r'^$', views.home, name='home'),

    url(r'^(?P<thread_id>[0-9]+)/$',views.thread, name='thread' ),

    url(r'^new/$', views.post_new, name='post_new'),

    url(r'^(?P<thread_id>[0-9]+)/comment/$', views.comment, name='comment'),

    url(r'^signup/$', views.signup, name='signup'),

    url(r'^login/$', auth_views.login,{'template_name': 'home/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/home/login/'}, name='logout'),

]

nil_co/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('home.urls')),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.timezone import now


class Category(models.Model):
    title = models.CharField(max_length=30)


    def __str__(self):
        return self.title



class Threads(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=30,default="nil")
    date = models.DateTimeField(max_length=10,auto_now_add=True, blank=True)
    topic_name = models.CharField(max_length=30)
    post_logo = models.CharField(max_length=30,default="nil")
    Question = models.CharField(max_length=1500)
    def __str__(self):
        return self.topic_name +' - '+self.name


class Comments(models.Model):
    thread = models.ForeignKey(Threads, on_delete=models.CASCADE)
    comment_name = models.CharField(max_length=30)
    date = models.DateTimeField(auto_now_add=True, blank=True)
    comment_body = models.CharField(max_length=1500)

    def __str__(self):
        return self.comment_name


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)

    @receiver(post_save, sender=User)
    def update_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    full_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    birth_date = forms.DateField(help_text='Required. Format: YYYY-MM-DD')
    class Meta:
        model = User
        fields = ('username','first_name','last_name','birth_date','email','password1','password2',)

home/views.py
from django.shortcuts import render,get_object_or_404,HttpResponseRedirect,redirect
from .models import Threads,Comments,Category,Profile
from .forms import SignUpForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
'''
class IndexView(generic.ListView):
    template_name = 'home/home.html'
    context_object_name = 'all_threads'

    def get_queryset(self):
        return Threads.objects.all()


class DetailView(generic.DetailView):
    model = Threads
    template_name = 'home/threadC.html'



'''    
def home(request):
    all_threads = Threads.objects.all()
    all_categories = Category.objects.all()
    print (request)
    context = {'all_threads': all_threads,'all_categories': all_categories}
    return render(request, 'home/home.html',context)


def threadc(request):
    return render(request, 'home/threadC.html')


def thread(request,thread_id):
    thread = get_object_or_404(Threads, pk=thread_id)
    context = {'thread': thread}
    return render(request, 'home/ThreadC.html', context)
'''
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('home')
    else:
        form = PostForm()
    return render(request, 'home/post_edit.html', {'form': form})
'''
def post_new(request):
    if request.method == 'POST':
        title = request.POST.get('topic_name', '')
        question = request.POST.get('Question', '')
        category = request.POST.get('category', '')
        print (title,question)
        obj = Threads(topic_name= title, Question = question,category = get_object_or_404(Category, pk=category))
        obj.name= request.user.username
        obj.save()
        all_threads = Threads.objects.all()
        context = {'all_threads': all_threads}
        return redirect('/home')
        return render(request, 'home/home.html', context)


def comment(request,thread_id):
    if request.method == 'POST':
        comment_body = request.POST.get('comment_body', '')

        obj = Comments(comment_body=comment_body)
        obj.comment_name= request.user.username
        obj.thread = get_object_or_404(Threads, pk=thread_id)
        obj.save()

        thread = get_object_or_404(Threads, pk=thread_id)
        context = {'thread': thread}
        return redirect('/home/'+thread_id)
        return render(request, '/home/ThreadC.html', context)


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.profile.birth_date = form.cleaned_data.get('birth_date')
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'home/signup.html', {'form': form})

home/templates/home/home.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<link href="{% static 'home/images/favicon.png' %}" rel="icon" type="image/x-icon" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="{% static 'home/desktop.css' %}" type="text/css" rel="stylesheet"  />
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link href="{% static 'home/style2.css' %}" type="text/css" rel="stylesheet" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="{% static 'home/myScript.js' %}">
	</script>
<style>
	#user{
padding-top:17px;
padding:17px 0px 0px 20px;
font-weight:bold;
}
</style>
</head>

<body>
<div class="navbar" style="z-index:2;">
	<ul>
		<li><h1>nil.co</h1><p class="caption">The ultimate forum for coders</p></li>
		<li class="right circle-propic" style="cursor:pointer" onclick="drop()" id="circular-propic">

		</li>
		<li class="right" id="user">Welcome {{request.user.first_name}} {{request.user.last_name}}</li>
		<li class="right"><input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for threads.."></li>

	</ul>
</div>
<div id="myDropdown" class="dropdown-content">
	<a href="#profile"><i class="fa fa-drivers-license-o"></i> view profile</a>
	<a href="#settings"><i class="material-icons">settings</i> Settings</a>
	<a href="logout/"><i class="material-icons">power_settings_new</i> Logout</a>
</div>
<div class="hamburger">
	<span style="font-size:30px;cursor:pointer" onclick="openNav()" id="hamburger">&#9776;</span>
</div>

<div id="mySidenav" class="sidenav">
	<a href="javascript:void(0)" class="closebtn" onclick="closeNav()" >&times;</a>
	<a href="#" class="current-sidemenu"style="color:white;"><img src="{% static 'home/images/home-ico.png' %}" width="20px"/> Home</a>
	<a href="javascript:void(0)" onclick="droprecent()"><img src="{% static 'home/images/recent-ico.png' %}" width="22px"/> Recently viewed <img src="{% static 'home/images/down-arrow.png' %}" width="10px"/></a>
	<div id="recent-threads" class="recent-threads1">
		<a href="threadC.html">C programming Doubts</a>
		<a href="#">PHP programming Doubts</a>
		<a href="#">Python programming Doubts</a>
	</div>
	<a href="javascript:void(0)" onclick="dropcategories()"><img src="{% static 'home/images/categories-ico.png' %}" width="20px"/> Categories  <img src="{% static 'home/images/down-arrow.png' %}" width="10px"/></a>
	<div id="categories" class="recent-threads1">
		<a href="#">C </a>
		<a href="#">PHP </a>
		<a href="#">Python </a>
		<a href="#">Django </a>
		<a href="#">Java </a>
		<a href="#">Android </a>
		<a href="#">All Categories </a>
	</div>
	<a href="#"><img src="{% static 'home/images/contact-ico.png' %}" width="20px"/> Contact</a>
</div>

<div id="main">

	<div class="main-heading">
		<div class="all-activity">All Activity</div>
		<button class="button" onclick="newTopic()">+ New Topic</button>
	</div>
	<div class="searchbox"><input type="text" id="myInput2" onkeyup="myFunction2()" placeholder="Search for threads.." ></div>
	<div class="thread-list">
		<table id="myTable">
			<tr class="tr tr-head">
				<th class="td-thread-pic th">Thread pic</th>
				<th class="thread-data th">Thread Description</th>
				<th class="replys th">Recent replys</th>
				<th class="thread-thumbs th">Upvotes and Downvotes</th>
			</tr>
			{% if all_threads %}
				{% for thread in all_threads %}
					<tr class="tr" onclick="location.href='/home/{{ thread.id }}/'">
						<td class="td-thread-pic td"><img src="{% static 'home/images/c.png' %}" class="thread-pic" width="64px" /></td>
						<td class="thread-data td">{{ thread.topic_name }}
							<div class="description">
								<div class="propic">	<img src="{% static 'home/images/propic.png' %}" width="30px"/> </div>
								<div class="username">
									{{ thread.date }}<br />
									{{ thread.name }}</div>
							</div>
						</td>
						<td class="replys td">+5</td>
						<td class="thread-thumbs td"><i class="material-icons" style="font-size:24px;color:orange">thumb_up</i>12 <i class="material-icons" style="font-size:24px;color:orange">thumb_down</i>4</td>
					</tr>
				{% endfor %}
			{% endif %}

		</table>
	</div>
</div>

<div id="newtopic1">

	<a href="javascript:void(0)" class="closebtn-newtopic" onclick="closeNewTopic()" style="text-decoration:none; color:black; font-size:30px;" >&times;</a>
	<div id="row1">
		<div class="col1"><img src="{% static 'home/images/propic.png' %}" width="60px"/></div>
		<div class="col2" style="color:black;">{{request.user.first_name}} {{request.user.last_name}}</div>
		<div class="col3" id="date" style="color:black;"></div>
	</div><br /><br /><br />
	<form method="POST" action="/home/new/"> {% csrf_token %}
		<div id="row1" style="color:black;">
			Category:
		<select name="category" style="width:200px;height:40px; font-size:17px; margin-bottom:10px;">
			{% for category in all_categories%}
			<option value="{{category.id}}">{{category.title}}</option>
			{% endfor %}
		</select><br></div><br>
		<textarea id="title" name="topic_name" placeholder="Title"></textarea>

		<button onclick="boldSelection ()" class="notselected button-style" id="bol"><b>B</b></button>
		<button onclick="italicsSelection ()"class="notselected button-style" id="italic"><i>I</i></button>
		<button onclick="underlineSelection ()"class="notselected button-style" id="under"><u>U</u></button><br/>

		<textarea id="myArea" name="Question" placeholder="Description of the thread...."></textarea>

		<button class="button1" onclick="closeNewTopic()">Cancel</button>
		<button type="submit" class="button1" onclick="closeNewTopic()">Post</button>

        </form>

</div>
<script>
var now = new Date();
var days = new Array('Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday');
var months = new Array('January','February','March','April','May','June','July','August','September','October','November','December');
var date = ((now.getDate()<10) ? "0" : "")+ now.getDate();
function fourdigits(number) {
return (number < 1000) ? number + 1900 : number;
}
today = days[now.getDay()] + ", " +
months[now.getMonth()] + " " +
date + ", " +
(fourdigits(now.getYear())) ;
document.getElementById("date").innerHTML = today;



</script>
<div id="black-background">

</div>



</body>
</html> 

home/templates/home/login.html
{% load staticfiles %}


<html>
<head>
	<meta charset="utf-8" />
<link href="{% static 'home/images/favicon.png' %}" rel="icon" type="image/x-icon" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="{% static 'home/mobile1.css' %}" type="text/css" rel="stylesheet" media="screen and (max-width: 768px)" />
<link href="{% static 'home/desktop1.css' %}" type="text/css" rel="stylesheet" media="screen and (min-width: 768px)" />
<style>

</style>
</head>

<body>
<div class="navbar">
	<ul>
	  <li><h1>nil.co</h1><p class="caption">The ultimate forum for coders</p></li>
	  <li class="right"><a href="/home/signup/" class="signup">Sign Up</a></li>
	</ul>
</div>

<!--<div class="head">
<h1>nil.co</h1>
<p>The ultimate forum for coders</p>
</div>

<div class="linker">
<a class="toplink"href="signup.html"><span></span>Sign Up</a>
</div>  -->

<div class="body ">
<h2>Welcome Back!</h2>
<form method="POST"> {% csrf_token %}
	{% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
	<input type="submit" value="Log In">
	<br><pre><a class="links" href="/home/signup/"><b>Do not have an account?</b></a></pre>
</form>
</div>

<div class="foot">
created by Nilay Pathak
</div>

</body>

</html>

home/templates/home/post_edit.html
<h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>

home/templates/home/signup.html
{% load staticfiles %}


<html>
<head>
	<meta charset="utf-8" />
<link href="{% static 'home/images/favicon.png' %}" rel="icon" type="image/x-icon" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="{% static 'home/mobile1.css' %}" type="text/css" rel="stylesheet" media="screen and (max-width: 768px)" />
<link href="{% static 'home/desktop1.css' %}" type="text/css" rel="stylesheet" media="screen and (min-width: 768px)" />
<style>
input[type=text],input[type=password],input[type=number] ,input[type=date],input[type=email]{
    width:98%;
    padding: 12px 20px;
    margin: 6px 3px;
	font-size:18px;
	color:rgb(115, 115, 115);
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
}
</style>
</head>

<body>

<div class="navbar">
	<ul>
	  <li><h1>nil.co</h1><p class="caption">The ultimate forum for coders</p></li>
	  <li class="right"><a href="/home/login/" class="signup">Log In</a></li>
	</ul>
</div>
<!--<div class="head">
<h1>nil.co</h1>
<p>The ultimate forum for coders</p>
</div>

<div class="linker">
<a class="toplink" href="index.html"><span></span>Log in</a>
</div>-->

<div class="body ">
<h2>Join us today!</h2>
<form method="POST" action="/home/signup/"> {% csrf_token %}
	{% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
	<input type="radio" name="gender" value="male" checked> Male
    <input type="radio" name="gender" value="female"> Female<br><br>
	<input type="checkbox" name="personalize" value="yes" >I accept the <a class="sentencelinks" href="#"><b>terms and conditions</b></a> of nil.co</a><br>
	<input type="submit" value="Sign Up"><br>
	<pre><a class="links" href="/home/login/"><b>Have an account? Log in</b></a></pre>
</form>
	</div>

<div class="foot">
created by Nilay Pathak
</div>

</body>

</html>

home/templates/home/threadC.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<link href="{% static 'home/images/favicon.png' %}" rel="icon" type="image/x-icon" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="{% static 'home/desktop.css' %}" type="text/css" rel="stylesheet"  />
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link href="{% static 'home/style2.css' %}" type="text/css" rel="stylesheet" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="{% static 'home/myScript.js' %}">
	</script>

</head>

<body>
<div class="navbar" style="z-index:2;">
	<ul>
		<li><h1>nil.co</h1><p class="caption">The ultimate forum for coders</p></li>
		<li class="right circle-propic" style="cursor:pointer" onclick="drop()">

		</li>
		<li class="right"><input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for threads.."></li>

	</ul>
</div>
<div id="myDropdown" class="dropdown-content">
	<a href="#profile"><i class="fa fa-drivers-license-o"></i> view profile</a>
	<a href="#settings"><i class="material-icons">settings</i> Settings</a>
	<a href="#logout"><i class="material-icons">power_settings_new</i> Logout</a>
</div>
<div class="hamburger">
	<span style="font-size:30px;cursor:pointer" onclick="openNav()" id="hamburger">&#9776;</span>
</div>

<div id="mySidenav" class="sidenav">
	<a href="javascript:void(0)" class="closebtn" onclick="closeNav()" >&times;</a>
	<a href="#" style="color:white;"><img src="{% static 'home/images/home-ico.png' %}" width="20px"/> Home</a>
	<a href="javascript:void(0)" onclick="droprecent()"><img src="{% static 'home/images/recent-ico.png' %}" width="22px"/> Recently viewed <img src="{% static 'home/images/down-arrow.png' %}" width="10px"/></a>
	<div id="recent-threads" class="recent-threads1">
		<a href="threadC.html">C programming Doubts</a>
		<a href="#">PHP programming Doubts</a>
		<a href="#">Python programming Doubts</a>
	</div>
	<a href="javascript:void(0)" onclick="dropcategories()"><img src="{% static 'home/images/categories-ico.png' %}" width="20px"/> Categories  <img src="{% static 'home/images/down-arrow.png' %}" width="10px"/></a>
	<div id="categories" class="recent-threads1">
		<a href="#" class="current-sidemenu">C </a>
		<a href="#">PHP </a>
		<a href="#">Python </a>
		<a href="#">Django </a>
		<a href="#">Java </a>
		<a href="#">Android </a>
		<a href="#">All Categories </a>
	</div>
	<a href="#"><img src="{% static 'home/images/contact-ico.png' %}" width="20px"/> Contact</a>
</div>


<div id="main">

	<div class="main-heading">
		<div class="all-activity">Programming in C</div>
		<button class="button" onclick="newReply()">+ Reply</button>
	</div>


	<div class="hor1">
		{{ thread.topic_name }}
	</div>
	<div class="contain1">
		<div class="hor2">
			<div class="hor2-ver1"><img src="{% static 'home/images/propic.png' %}" width="100px"/></div>
			<div class="hor2-ver2">
				<div class="row1">
					<div class="nameofwriter">{{ thread.name }} </div>
					<div class="dop"> .12 May,2017</div></div>
				<div class="decription-thread">

					<p>
						{{ thread.Question }}
					</p>
				</div>
			</div>
		</div>
		<div class="hor3">
			<i class="material-icons" style="font-size:24px;">thumb_up</i>19 <i class="material-icons" style="font-size:24px;">thumb_down</i>7
		</div>

	</div>
	<div class="replies">
		Replies
	</div>
	{% if thread.comments_set.all %}
	{% for comment in thread.comments_set.all %}
	<div class="contain2">
		<div class="hor2">
			<div class="hor2-ver1  rep1"><img src="{% static 'home/images/propic.png' %}" width="60px"/></div>
			<div class="hor2-ver2">
				<div class="row1">
					<div class="nameofwriter">{{ comment.comment_name }}</div>
					<div class="dop">{{comment.date}}</div></div>
				<div class="decription-thread" id={{comment.id}}>
				</div>
				<script> var body=reply("{{comment.comment_body}}");
				document.getElementById({{comment.id}}).innerHTML = body ;</script>
			</div>
		</div>
		<div class="hor3">
			<i class="material-icons" style="font-size:24px;">thumb_up</i>7 <i class="material-icons" style="font-size:24px;">thumb_down</i>4
		</div>
	</div>
	{% endfor %}
	{% endif %}

	<div class="main-heading">
		<button class="button foot_replybutton" onclick="newReply()">+ Reply</button>
	</div>
</div>

<div id="newtopic1">

	<a href="javascript:void(0)" class="closebtn-newtopic" onclick="closeNewTopic()" >&times;</a>
	<div id="row1">
		<div class="col1"><img src="propic.png" width="60px"/></div>
		<div class="col2" style="color:black;">{{request.user.first_name}} {{request.user.last_name}}</div>
		<div class="col3" id="date" style="color:black;"></div>
	</div>
	<form method="POST" action="/home/{{ thread.id }}/comment/"> {% csrf_token %}


		<button onclick="boldSelection ()" class="notselected button-style" id="bol"><b>B</b></button>
		<button onclick="italicsSelection ()"class="notselected button-style" id="italic"><i>I</i></button>
		<button onclick="underlineSelection ()"class="notselected button-style" id="under"><u>U</u></button><br/>


		<textarea id="myArea" name="comment_body" placeholder="Write your reply here..."></textarea>



		<button class="button1">Reply</button>
	</form>
<button class="button1" onclick="closeNewTopic()">Cancel</button>
</div>
<script>
var now = new Date();
var days = new Array('Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday');
var months = new Array('January','February','March','April','May','June','July','August','September','October','November','December');
var date = ((now.getDate()<10) ? "0" : "")+ now.getDate();
function fourdigits(number) {
return (number < 1000) ? number + 1900 : number;
}
today = days[now.getDay()] + ", " +
months[now.getMonth()] + " " +
date + ", " +
(fourdigits(now.getYear())) ;
document.getElementById("date").innerHTML = today;


$.fn.followTo = function (pos) {
    var $this = this,
        $window = $(window);

    $window.scroll(function (e) {
        if ($window.scrollTop() > pos) {
            $this.css({
                position: 'fixed',
                top: 130
            });
        } else {
            $this.css({
                position: 'absolute',
                top: 230
            });
        }
    });
};

$('#myInput2').followTo(110);
</script>
<div id="black-background">

</div>



</body>
</html> 